// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.15.7
// source: tits/v1/tits.proto

package titspb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Tits struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// ID of the tits.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// URL of the tits.
	ImgUrl string `protobuf:"bytes,2,opt,name=img_url,json=imgUrl,proto3" json:"img_url,omitempty"`
	// Current rating of the tits.
	// Can be negative, if tits is from abyss.
	Rating int64 `protobuf:"varint,3,opt,name=rating,proto3" json:"rating,omitempty"`
}

func (x *Tits) Reset() {
	*x = Tits{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tits_v1_tits_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Tits) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tits) ProtoMessage() {}

func (x *Tits) ProtoReflect() protoreflect.Message {
	mi := &file_tits_v1_tits_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tits.ProtoReflect.Descriptor instead.
func (*Tits) Descriptor() ([]byte, []int) {
	return file_tits_v1_tits_proto_rawDescGZIP(), []int{0}
}

func (x *Tits) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Tits) GetImgUrl() string {
	if x != nil {
		return x.ImgUrl
	}
	return ""
}

func (x *Tits) GetRating() int64 {
	if x != nil {
		return x.Rating
	}
	return 0
}

type TitsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *TitsRequest) Reset() {
	*x = TitsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tits_v1_tits_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TitsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TitsRequest) ProtoMessage() {}

func (x *TitsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tits_v1_tits_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TitsRequest.ProtoReflect.Descriptor instead.
func (*TitsRequest) Descriptor() ([]byte, []int) {
	return file_tits_v1_tits_proto_rawDescGZIP(), []int{1}
}

// Response for GetTits.
// Returns pair of tits.
type TitsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Pair of tits.
	Tits []*Tits `protobuf:"bytes,1,rep,name=tits,proto3" json:"tits,omitempty"`
}

func (x *TitsResponse) Reset() {
	*x = TitsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tits_v1_tits_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TitsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TitsResponse) ProtoMessage() {}

func (x *TitsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tits_v1_tits_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TitsResponse.ProtoReflect.Descriptor instead.
func (*TitsResponse) Descriptor() ([]byte, []int) {
	return file_tits_v1_tits_proto_rawDescGZIP(), []int{2}
}

func (x *TitsResponse) GetTits() []*Tits {
	if x != nil {
		return x.Tits
	}
	return nil
}

// Request for Vote.
type VoteRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// ID of the tits.
	TitsId string `protobuf:"bytes,1,opt,name=tits_id,json=titsId,proto3" json:"tits_id,omitempty"`
}

func (x *VoteRequest) Reset() {
	*x = VoteRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tits_v1_tits_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VoteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VoteRequest) ProtoMessage() {}

func (x *VoteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tits_v1_tits_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VoteRequest.ProtoReflect.Descriptor instead.
func (*VoteRequest) Descriptor() ([]byte, []int) {
	return file_tits_v1_tits_proto_rawDescGZIP(), []int{3}
}

func (x *VoteRequest) GetTitsId() string {
	if x != nil {
		return x.TitsId
	}
	return ""
}

var File_tits_v1_tits_proto protoreflect.FileDescriptor

var file_tits_v1_tits_proto_rawDesc = []byte{
	0x0a, 0x12, 0x74, 0x69, 0x74, 0x73, 0x2f, 0x76, 0x31, 0x2f, 0x74, 0x69, 0x74, 0x73, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x61, 0x70, 0x69, 0x73, 0x2e, 0x74, 0x69, 0x74, 0x73, 0x2e,
	0x76, 0x31, 0x22, 0x47, 0x0a, 0x04, 0x54, 0x69, 0x74, 0x73, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x69, 0x6d,
	0x67, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x69, 0x6d, 0x67,
	0x55, 0x72, 0x6c, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x06, 0x72, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x22, 0x0d, 0x0a, 0x0b, 0x54,
	0x69, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x36, 0x0a, 0x0c, 0x54, 0x69,
	0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x26, 0x0a, 0x04, 0x74, 0x69,
	0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x61, 0x70, 0x69, 0x73, 0x2e,
	0x74, 0x69, 0x74, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x54, 0x69, 0x74, 0x73, 0x52, 0x04, 0x74, 0x69,
	0x74, 0x73, 0x22, 0x26, 0x0a, 0x0b, 0x56, 0x6f, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x17, 0x0a, 0x07, 0x74, 0x69, 0x74, 0x73, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x74, 0x69, 0x74, 0x73, 0x49, 0x64, 0x32, 0x92, 0x01, 0x0a, 0x0b, 0x54,
	0x69, 0x74, 0x73, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x42, 0x0a, 0x07, 0x47, 0x65,
	0x74, 0x54, 0x69, 0x74, 0x73, 0x12, 0x19, 0x2e, 0x61, 0x70, 0x69, 0x73, 0x2e, 0x74, 0x69, 0x74,
	0x73, 0x2e, 0x76, 0x31, 0x2e, 0x54, 0x69, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x1a, 0x2e, 0x61, 0x70, 0x69, 0x73, 0x2e, 0x74, 0x69, 0x74, 0x73, 0x2e, 0x76, 0x31, 0x2e,
	0x54, 0x69, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x3f,
	0x0a, 0x04, 0x56, 0x6f, 0x74, 0x65, 0x12, 0x19, 0x2e, 0x61, 0x70, 0x69, 0x73, 0x2e, 0x74, 0x69,
	0x74, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x56, 0x6f, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x1a, 0x2e, 0x61, 0x70, 0x69, 0x73, 0x2e, 0x74, 0x69, 0x74, 0x73, 0x2e, 0x76, 0x31,
	0x2e, 0x54, 0x69, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42,
	0x15, 0x5a, 0x13, 0x61, 0x70, 0x69, 0x73, 0x2f, 0x74, 0x69, 0x74, 0x73, 0x2f, 0x76, 0x31, 0x3b,
	0x74, 0x69, 0x74, 0x73, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_tits_v1_tits_proto_rawDescOnce sync.Once
	file_tits_v1_tits_proto_rawDescData = file_tits_v1_tits_proto_rawDesc
)

func file_tits_v1_tits_proto_rawDescGZIP() []byte {
	file_tits_v1_tits_proto_rawDescOnce.Do(func() {
		file_tits_v1_tits_proto_rawDescData = protoimpl.X.CompressGZIP(file_tits_v1_tits_proto_rawDescData)
	})
	return file_tits_v1_tits_proto_rawDescData
}

var file_tits_v1_tits_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_tits_v1_tits_proto_goTypes = []interface{}{
	(*Tits)(nil),         // 0: apis.tits.v1.Tits
	(*TitsRequest)(nil),  // 1: apis.tits.v1.TitsRequest
	(*TitsResponse)(nil), // 2: apis.tits.v1.TitsResponse
	(*VoteRequest)(nil),  // 3: apis.tits.v1.VoteRequest
}
var file_tits_v1_tits_proto_depIdxs = []int32{
	0, // 0: apis.tits.v1.TitsResponse.tits:type_name -> apis.tits.v1.Tits
	1, // 1: apis.tits.v1.TitsService.GetTits:input_type -> apis.tits.v1.TitsRequest
	3, // 2: apis.tits.v1.TitsService.Vote:input_type -> apis.tits.v1.VoteRequest
	2, // 3: apis.tits.v1.TitsService.GetTits:output_type -> apis.tits.v1.TitsResponse
	2, // 4: apis.tits.v1.TitsService.Vote:output_type -> apis.tits.v1.TitsResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_tits_v1_tits_proto_init() }
func file_tits_v1_tits_proto_init() {
	if File_tits_v1_tits_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_tits_v1_tits_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Tits); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tits_v1_tits_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TitsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tits_v1_tits_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TitsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tits_v1_tits_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VoteRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_tits_v1_tits_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_tits_v1_tits_proto_goTypes,
		DependencyIndexes: file_tits_v1_tits_proto_depIdxs,
		MessageInfos:      file_tits_v1_tits_proto_msgTypes,
	}.Build()
	File_tits_v1_tits_proto = out.File
	file_tits_v1_tits_proto_rawDesc = nil
	file_tits_v1_tits_proto_goTypes = nil
	file_tits_v1_tits_proto_depIdxs = nil
}
