// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.15.7
// source: tits/v1/tits.proto

package titspb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// TitsServiceClient is the client API for TitsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TitsServiceClient interface {
	// Get pair tits to compare.
	GetTits(ctx context.Context, in *TitsRequest, opts ...grpc.CallOption) (*TitsResponse, error)
	// Vote for one of two tits.
	Vote(ctx context.Context, in *VoteRequest, opts ...grpc.CallOption) (*TitsResponse, error)
}

type titsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTitsServiceClient(cc grpc.ClientConnInterface) TitsServiceClient {
	return &titsServiceClient{cc}
}

func (c *titsServiceClient) GetTits(ctx context.Context, in *TitsRequest, opts ...grpc.CallOption) (*TitsResponse, error) {
	out := new(TitsResponse)
	err := c.cc.Invoke(ctx, "/apis.tits.v1.TitsService/GetTits", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *titsServiceClient) Vote(ctx context.Context, in *VoteRequest, opts ...grpc.CallOption) (*TitsResponse, error) {
	out := new(TitsResponse)
	err := c.cc.Invoke(ctx, "/apis.tits.v1.TitsService/Vote", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TitsServiceServer is the server API for TitsService service.
// All implementations must embed UnimplementedTitsServiceServer
// for forward compatibility
type TitsServiceServer interface {
	// Get pair tits to compare.
	GetTits(context.Context, *TitsRequest) (*TitsResponse, error)
	// Vote for one of two tits.
	Vote(context.Context, *VoteRequest) (*TitsResponse, error)
	mustEmbedUnimplementedTitsServiceServer()
}

// UnimplementedTitsServiceServer must be embedded to have forward compatible implementations.
type UnimplementedTitsServiceServer struct {
}

func (UnimplementedTitsServiceServer) GetTits(context.Context, *TitsRequest) (*TitsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTits not implemented")
}
func (UnimplementedTitsServiceServer) Vote(context.Context, *VoteRequest) (*TitsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Vote not implemented")
}
func (UnimplementedTitsServiceServer) mustEmbedUnimplementedTitsServiceServer() {}

// UnsafeTitsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TitsServiceServer will
// result in compilation errors.
type UnsafeTitsServiceServer interface {
	mustEmbedUnimplementedTitsServiceServer()
}

func RegisterTitsServiceServer(s grpc.ServiceRegistrar, srv TitsServiceServer) {
	s.RegisterService(&TitsService_ServiceDesc, srv)
}

func _TitsService_GetTits_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TitsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TitsServiceServer).GetTits(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/apis.tits.v1.TitsService/GetTits",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TitsServiceServer).GetTits(ctx, req.(*TitsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TitsService_Vote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VoteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TitsServiceServer).Vote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/apis.tits.v1.TitsService/Vote",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TitsServiceServer).Vote(ctx, req.(*VoteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TitsService_ServiceDesc is the grpc.ServiceDesc for TitsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TitsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "apis.tits.v1.TitsService",
	HandlerType: (*TitsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetTits",
			Handler:    _TitsService_GetTits_Handler,
		},
		{
			MethodName: "Vote",
			Handler:    _TitsService_Vote_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "tits/v1/tits.proto",
}
